[workspace]
members = [
	"moq-transfork",
	"moq-relay",
	"moq-clock",
	"moq-native",
	"moq-karp",
	"moq-web",
	"moq-async",
]
resolver = "2"

[workspace.dependencies]
# Make it easy to test web-transport changes
#web-transport = { path = "../web-transport-rs/web-transport" }
web-transport = "0.8"

[profile.release.package.moq-web]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
